// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-bundle-api/slack"
	"sync"
)

// Ensure, that ClienterMock does implement slack.Clienter.
// If this is not the case, regenerate this file with moq.
var _ slack.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of slack.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked slack.Clienter
//		mockedClienter := &ClienterMock{
//			ChannelsFunc: func() slack.Channels {
//				panic("mock out the Channels method")
//			},
//			SendErrorFunc: func(ctx context.Context, channel string, summary string, err error, details map[string]interface{}) error {
//				panic("mock out the SendError method")
//			},
//		}
//
//		// use mockedClienter in code that requires slack.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// ChannelsFunc mocks the Channels method.
	ChannelsFunc func() slack.Channels

	// SendErrorFunc mocks the SendError method.
	SendErrorFunc func(ctx context.Context, channel string, summary string, err error, details map[string]interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// Channels holds details about calls to the Channels method.
		Channels []struct {
		}
		// SendError holds details about calls to the SendError method.
		SendError []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Channel is the channel argument value.
			Channel string
			// Summary is the summary argument value.
			Summary string
			// Err is the err argument value.
			Err error
			// Details is the details argument value.
			Details map[string]interface{}
		}
	}
	lockChannels  sync.RWMutex
	lockSendError sync.RWMutex
}

// Channels calls ChannelsFunc.
func (mock *ClienterMock) Channels() slack.Channels {
	if mock.ChannelsFunc == nil {
		panic("ClienterMock.ChannelsFunc: method is nil but Clienter.Channels was just called")
	}
	callInfo := struct {
	}{}
	mock.lockChannels.Lock()
	mock.calls.Channels = append(mock.calls.Channels, callInfo)
	mock.lockChannels.Unlock()
	return mock.ChannelsFunc()
}

// ChannelsCalls gets all the calls that were made to Channels.
// Check the length with:
//
//	len(mockedClienter.ChannelsCalls())
func (mock *ClienterMock) ChannelsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockChannels.RLock()
	calls = mock.calls.Channels
	mock.lockChannels.RUnlock()
	return calls
}

// SendError calls SendErrorFunc.
func (mock *ClienterMock) SendError(ctx context.Context, channel string, summary string, err error, details map[string]interface{}) error {
	if mock.SendErrorFunc == nil {
		panic("ClienterMock.SendErrorFunc: method is nil but Clienter.SendError was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Channel string
		Summary string
		Err     error
		Details map[string]interface{}
	}{
		Ctx:     ctx,
		Channel: channel,
		Summary: summary,
		Err:     err,
		Details: details,
	}
	mock.lockSendError.Lock()
	mock.calls.SendError = append(mock.calls.SendError, callInfo)
	mock.lockSendError.Unlock()
	return mock.SendErrorFunc(ctx, channel, summary, err, details)
}

// SendErrorCalls gets all the calls that were made to SendError.
// Check the length with:
//
//	len(mockedClienter.SendErrorCalls())
func (mock *ClienterMock) SendErrorCalls() []struct {
	Ctx     context.Context
	Channel string
	Summary string
	Err     error
	Details map[string]interface{}
} {
	var calls []struct {
		Ctx     context.Context
		Channel string
		Summary string
		Err     error
		Details map[string]interface{}
	}
	mock.lockSendError.RLock()
	calls = mock.calls.SendError
	mock.lockSendError.RUnlock()
	return calls
}
