// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/ONSdigital/dis-bundle-api/slack"
)

// Ensure, that ClienterMock does implement slack.Clienter.
// If this is not the case, regenerate this file with moq.
var _ slack.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of slack.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked slack.Clienter
//		mockedClienter := &ClienterMock{
//			SendAlarmFunc: func(ctx context.Context, summary string, err error, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the SendAlarm method")
//			},
//			SendInfoFunc: func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the SendInfo method")
//			},
//			SendPublishLogFunc: func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the SendPublishLog method")
//			},
//			SendWarningFunc: func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the SendWarning method")
//			},
//			UpdatePublishLogFunc: func(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the UpdatePublishLog method")
//			},
//			UpdatePublishLogAsAlarmFunc: func(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error) {
//				panic("mock out the UpdatePublishLogAsAlarm method")
//			},
//		}
//
//		// use mockedClienter in code that requires slack.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// SendAlarmFunc mocks the SendAlarm method.
	SendAlarmFunc func(ctx context.Context, summary string, err error, fields []slack.Field) (*slack.MessageRef, error)

	// SendInfoFunc mocks the SendInfo method.
	SendInfoFunc func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error)

	// SendPublishLogFunc mocks the SendPublishLog method.
	SendPublishLogFunc func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error)

	// SendWarningFunc mocks the SendWarning method.
	SendWarningFunc func(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error)

	// UpdatePublishLogFunc mocks the UpdatePublishLog method.
	UpdatePublishLogFunc func(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error)

	// UpdatePublishLogAsAlarmFunc mocks the UpdatePublishLogAsAlarm method.
	UpdatePublishLogAsAlarmFunc func(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendAlarm holds details about calls to the SendAlarm method.
		SendAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Err is the err argument value.
			Err error
			// Fields is the fields argument value.
			Fields []slack.Field
		}
		// SendInfo holds details about calls to the SendInfo method.
		SendInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Fields is the fields argument value.
			Fields []slack.Field
		}
		// SendPublishLog holds details about calls to the SendPublishLog method.
		SendPublishLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Fields is the fields argument value.
			Fields []slack.Field
		}
		// SendWarning holds details about calls to the SendWarning method.
		SendWarning []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Fields is the fields argument value.
			Fields []slack.Field
		}
		// UpdatePublishLog holds details about calls to the UpdatePublishLog method.
		UpdatePublishLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref *slack.MessageRef
			// Summary is the summary argument value.
			Summary string
			// Fields is the fields argument value.
			Fields []slack.Field
		}
		// UpdatePublishLogAsAlarm holds details about calls to the UpdatePublishLogAsAlarm method.
		UpdatePublishLogAsAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref *slack.MessageRef
			// Summary is the summary argument value.
			Summary string
			// Fields is the fields argument value.
			Fields []slack.Field
		}
	}
	lockSendAlarm               sync.RWMutex
	lockSendInfo                sync.RWMutex
	lockSendPublishLog          sync.RWMutex
	lockSendWarning             sync.RWMutex
	lockUpdatePublishLog        sync.RWMutex
	lockUpdatePublishLogAsAlarm sync.RWMutex
}

// SendAlarm calls SendAlarmFunc.
func (mock *ClienterMock) SendAlarm(ctx context.Context, summary string, err error, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.SendAlarmFunc == nil {
		panic("ClienterMock.SendAlarmFunc: method is nil but Clienter.SendAlarm was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Err     error
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Summary: summary,
		Err:     err,
		Fields:  fields,
	}
	mock.lockSendAlarm.Lock()
	mock.calls.SendAlarm = append(mock.calls.SendAlarm, callInfo)
	mock.lockSendAlarm.Unlock()
	return mock.SendAlarmFunc(ctx, summary, err, fields)
}

// SendAlarmCalls gets all the calls that were made to SendAlarm.
// Check the length with:
//
//	len(mockedClienter.SendAlarmCalls())
func (mock *ClienterMock) SendAlarmCalls() []struct {
	Ctx     context.Context
	Summary string
	Err     error
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Err     error
		Fields  []slack.Field
	}
	mock.lockSendAlarm.RLock()
	calls = mock.calls.SendAlarm
	mock.lockSendAlarm.RUnlock()
	return calls
}

// SendInfo calls SendInfoFunc.
func (mock *ClienterMock) SendInfo(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.SendInfoFunc == nil {
		panic("ClienterMock.SendInfoFunc: method is nil but Clienter.SendInfo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Summary: summary,
		Fields:  fields,
	}
	mock.lockSendInfo.Lock()
	mock.calls.SendInfo = append(mock.calls.SendInfo, callInfo)
	mock.lockSendInfo.Unlock()
	return mock.SendInfoFunc(ctx, summary, fields)
}

// SendInfoCalls gets all the calls that were made to SendInfo.
// Check the length with:
//
//	len(mockedClienter.SendInfoCalls())
func (mock *ClienterMock) SendInfoCalls() []struct {
	Ctx     context.Context
	Summary string
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}
	mock.lockSendInfo.RLock()
	calls = mock.calls.SendInfo
	mock.lockSendInfo.RUnlock()
	return calls
}

// SendPublishLog calls SendPublishLogFunc.
func (mock *ClienterMock) SendPublishLog(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.SendPublishLogFunc == nil {
		panic("ClienterMock.SendPublishLogFunc: method is nil but Clienter.SendPublishLog was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Summary: summary,
		Fields:  fields,
	}
	mock.lockSendPublishLog.Lock()
	mock.calls.SendPublishLog = append(mock.calls.SendPublishLog, callInfo)
	mock.lockSendPublishLog.Unlock()
	return mock.SendPublishLogFunc(ctx, summary, fields)
}

// SendPublishLogCalls gets all the calls that were made to SendPublishLog.
// Check the length with:
//
//	len(mockedClienter.SendPublishLogCalls())
func (mock *ClienterMock) SendPublishLogCalls() []struct {
	Ctx     context.Context
	Summary string
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}
	mock.lockSendPublishLog.RLock()
	calls = mock.calls.SendPublishLog
	mock.lockSendPublishLog.RUnlock()
	return calls
}

// SendWarning calls SendWarningFunc.
func (mock *ClienterMock) SendWarning(ctx context.Context, summary string, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.SendWarningFunc == nil {
		panic("ClienterMock.SendWarningFunc: method is nil but Clienter.SendWarning was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Summary: summary,
		Fields:  fields,
	}
	mock.lockSendWarning.Lock()
	mock.calls.SendWarning = append(mock.calls.SendWarning, callInfo)
	mock.lockSendWarning.Unlock()
	return mock.SendWarningFunc(ctx, summary, fields)
}

// SendWarningCalls gets all the calls that were made to SendWarning.
// Check the length with:
//
//	len(mockedClienter.SendWarningCalls())
func (mock *ClienterMock) SendWarningCalls() []struct {
	Ctx     context.Context
	Summary string
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Fields  []slack.Field
	}
	mock.lockSendWarning.RLock()
	calls = mock.calls.SendWarning
	mock.lockSendWarning.RUnlock()
	return calls
}

// UpdatePublishLog calls UpdatePublishLogFunc.
func (mock *ClienterMock) UpdatePublishLog(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.UpdatePublishLogFunc == nil {
		panic("ClienterMock.UpdatePublishLogFunc: method is nil but Clienter.UpdatePublishLog was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Summary string
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Ref:     ref,
		Summary: summary,
		Fields:  fields,
	}
	mock.lockUpdatePublishLog.Lock()
	mock.calls.UpdatePublishLog = append(mock.calls.UpdatePublishLog, callInfo)
	mock.lockUpdatePublishLog.Unlock()
	return mock.UpdatePublishLogFunc(ctx, ref, summary, fields)
}

// UpdatePublishLogCalls gets all the calls that were made to UpdatePublishLog.
// Check the length with:
//
//	len(mockedClienter.UpdatePublishLogCalls())
func (mock *ClienterMock) UpdatePublishLogCalls() []struct {
	Ctx     context.Context
	Ref     *slack.MessageRef
	Summary string
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Summary string
		Fields  []slack.Field
	}
	mock.lockUpdatePublishLog.RLock()
	calls = mock.calls.UpdatePublishLog
	mock.lockUpdatePublishLog.RUnlock()
	return calls
}

// UpdatePublishLogAsAlarm calls UpdatePublishLogAsAlarmFunc.
func (mock *ClienterMock) UpdatePublishLogAsAlarm(ctx context.Context, ref *slack.MessageRef, summary string, fields []slack.Field) (*slack.MessageRef, error) {
	if mock.UpdatePublishLogAsAlarmFunc == nil {
		panic("ClienterMock.UpdatePublishLogAsAlarmFunc: method is nil but Clienter.UpdatePublishLogAsAlarm was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Summary string
		Fields  []slack.Field
	}{
		Ctx:     ctx,
		Ref:     ref,
		Summary: summary,
		Fields:  fields,
	}
	mock.lockUpdatePublishLogAsAlarm.Lock()
	mock.calls.UpdatePublishLogAsAlarm = append(mock.calls.UpdatePublishLogAsAlarm, callInfo)
	mock.lockUpdatePublishLogAsAlarm.Unlock()
	return mock.UpdatePublishLogAsAlarmFunc(ctx, ref, summary, fields)
}

// UpdatePublishLogAsAlarmCalls gets all the calls that were made to UpdatePublishLogAsAlarm.
// Check the length with:
//
//	len(mockedClienter.UpdatePublishLogAsAlarmCalls())
func (mock *ClienterMock) UpdatePublishLogAsAlarmCalls() []struct {
	Ctx     context.Context
	Ref     *slack.MessageRef
	Summary string
	Fields  []slack.Field
} {
	var calls []struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Summary string
		Fields  []slack.Field
	}
	mock.lockUpdatePublishLogAsAlarm.RLock()
	calls = mock.calls.UpdatePublishLogAsAlarm
	mock.lockUpdatePublishLogAsAlarm.RUnlock()
	return calls
}
