// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-bundle-api/slack"
	"sync"
	"time"
)

// Ensure, that ClienterMock does implement slack.Clienter.
// If this is not the case, regenerate this file with moq.
var _ slack.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of slack.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked slack.Clienter
//		mockedClienter := &ClienterMock{
//			GetTimeoutFunc: func() time.Duration {
//				panic("mock out the GetTimeout method")
//			},
//			SendAlarmFunc: func(ctx context.Context, title string, err error, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
//				panic("mock out the SendAlarm method")
//			},
//			SendInfoFunc: func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
//				panic("mock out the SendInfo method")
//			},
//			SendPublishLogFunc: func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
//				panic("mock out the SendPublishLog method")
//			},
//			SendWarningFunc: func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
//				panic("mock out the SendWarning method")
//			},
//			UpdateMessageFunc: func(ctx context.Context, ref *slack.MessageRef, title string, err error, details []slack.Detail, links []slack.Link, color slack.Colour, emoji slack.Emoji) (*slack.MessageRef, error) {
//				panic("mock out the UpdateMessage method")
//			},
//		}
//
//		// use mockedClienter in code that requires slack.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// GetTimeoutFunc mocks the GetTimeout method.
	GetTimeoutFunc func() time.Duration

	// SendAlarmFunc mocks the SendAlarm method.
	SendAlarmFunc func(ctx context.Context, title string, err error, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error)

	// SendInfoFunc mocks the SendInfo method.
	SendInfoFunc func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error)

	// SendPublishLogFunc mocks the SendPublishLog method.
	SendPublishLogFunc func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error)

	// SendWarningFunc mocks the SendWarning method.
	SendWarningFunc func(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error)

	// UpdateMessageFunc mocks the UpdateMessage method.
	UpdateMessageFunc func(ctx context.Context, ref *slack.MessageRef, title string, err error, details []slack.Detail, links []slack.Link, color slack.Colour, emoji slack.Emoji) (*slack.MessageRef, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTimeout holds details about calls to the GetTimeout method.
		GetTimeout []struct {
		}
		// SendAlarm holds details about calls to the SendAlarm method.
		SendAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Err is the err argument value.
			Err error
			// Details is the details argument value.
			Details []slack.Detail
			// Links is the links argument value.
			Links []slack.Link
		}
		// SendInfo holds details about calls to the SendInfo method.
		SendInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Details is the details argument value.
			Details []slack.Detail
			// Links is the links argument value.
			Links []slack.Link
		}
		// SendPublishLog holds details about calls to the SendPublishLog method.
		SendPublishLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Details is the details argument value.
			Details []slack.Detail
			// Links is the links argument value.
			Links []slack.Link
		}
		// SendWarning holds details about calls to the SendWarning method.
		SendWarning []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Details is the details argument value.
			Details []slack.Detail
			// Links is the links argument value.
			Links []slack.Link
		}
		// UpdateMessage holds details about calls to the UpdateMessage method.
		UpdateMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref *slack.MessageRef
			// Title is the title argument value.
			Title string
			// Err is the err argument value.
			Err error
			// Details is the details argument value.
			Details []slack.Detail
			// Links is the links argument value.
			Links []slack.Link
			// Color is the color argument value.
			Color slack.Colour
			// Emoji is the emoji argument value.
			Emoji slack.Emoji
		}
	}
	lockGetTimeout     sync.RWMutex
	lockSendAlarm      sync.RWMutex
	lockSendInfo       sync.RWMutex
	lockSendPublishLog sync.RWMutex
	lockSendWarning    sync.RWMutex
	lockUpdateMessage  sync.RWMutex
}

// GetTimeout calls GetTimeoutFunc.
func (mock *ClienterMock) GetTimeout() time.Duration {
	if mock.GetTimeoutFunc == nil {
		panic("ClienterMock.GetTimeoutFunc: method is nil but Clienter.GetTimeout was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTimeout.Lock()
	mock.calls.GetTimeout = append(mock.calls.GetTimeout, callInfo)
	mock.lockGetTimeout.Unlock()
	return mock.GetTimeoutFunc()
}

// GetTimeoutCalls gets all the calls that were made to GetTimeout.
// Check the length with:
//
//	len(mockedClienter.GetTimeoutCalls())
func (mock *ClienterMock) GetTimeoutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTimeout.RLock()
	calls = mock.calls.GetTimeout
	mock.lockGetTimeout.RUnlock()
	return calls
}

// SendAlarm calls SendAlarmFunc.
func (mock *ClienterMock) SendAlarm(ctx context.Context, title string, err error, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
	if mock.SendAlarmFunc == nil {
		panic("ClienterMock.SendAlarmFunc: method is nil but Clienter.SendAlarm was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Title   string
		Err     error
		Details []slack.Detail
		Links   []slack.Link
	}{
		Ctx:     ctx,
		Title:   title,
		Err:     err,
		Details: details,
		Links:   links,
	}
	mock.lockSendAlarm.Lock()
	mock.calls.SendAlarm = append(mock.calls.SendAlarm, callInfo)
	mock.lockSendAlarm.Unlock()
	return mock.SendAlarmFunc(ctx, title, err, details, links)
}

// SendAlarmCalls gets all the calls that were made to SendAlarm.
// Check the length with:
//
//	len(mockedClienter.SendAlarmCalls())
func (mock *ClienterMock) SendAlarmCalls() []struct {
	Ctx     context.Context
	Title   string
	Err     error
	Details []slack.Detail
	Links   []slack.Link
} {
	var calls []struct {
		Ctx     context.Context
		Title   string
		Err     error
		Details []slack.Detail
		Links   []slack.Link
	}
	mock.lockSendAlarm.RLock()
	calls = mock.calls.SendAlarm
	mock.lockSendAlarm.RUnlock()
	return calls
}

// SendInfo calls SendInfoFunc.
func (mock *ClienterMock) SendInfo(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
	if mock.SendInfoFunc == nil {
		panic("ClienterMock.SendInfoFunc: method is nil but Clienter.SendInfo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}{
		Ctx:     ctx,
		Title:   title,
		Details: details,
		Links:   links,
	}
	mock.lockSendInfo.Lock()
	mock.calls.SendInfo = append(mock.calls.SendInfo, callInfo)
	mock.lockSendInfo.Unlock()
	return mock.SendInfoFunc(ctx, title, details, links)
}

// SendInfoCalls gets all the calls that were made to SendInfo.
// Check the length with:
//
//	len(mockedClienter.SendInfoCalls())
func (mock *ClienterMock) SendInfoCalls() []struct {
	Ctx     context.Context
	Title   string
	Details []slack.Detail
	Links   []slack.Link
} {
	var calls []struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}
	mock.lockSendInfo.RLock()
	calls = mock.calls.SendInfo
	mock.lockSendInfo.RUnlock()
	return calls
}

// SendPublishLog calls SendPublishLogFunc.
func (mock *ClienterMock) SendPublishLog(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
	if mock.SendPublishLogFunc == nil {
		panic("ClienterMock.SendPublishLogFunc: method is nil but Clienter.SendPublishLog was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}{
		Ctx:     ctx,
		Title:   title,
		Details: details,
		Links:   links,
	}
	mock.lockSendPublishLog.Lock()
	mock.calls.SendPublishLog = append(mock.calls.SendPublishLog, callInfo)
	mock.lockSendPublishLog.Unlock()
	return mock.SendPublishLogFunc(ctx, title, details, links)
}

// SendPublishLogCalls gets all the calls that were made to SendPublishLog.
// Check the length with:
//
//	len(mockedClienter.SendPublishLogCalls())
func (mock *ClienterMock) SendPublishLogCalls() []struct {
	Ctx     context.Context
	Title   string
	Details []slack.Detail
	Links   []slack.Link
} {
	var calls []struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}
	mock.lockSendPublishLog.RLock()
	calls = mock.calls.SendPublishLog
	mock.lockSendPublishLog.RUnlock()
	return calls
}

// SendWarning calls SendWarningFunc.
func (mock *ClienterMock) SendWarning(ctx context.Context, title string, details []slack.Detail, links []slack.Link) (*slack.MessageRef, error) {
	if mock.SendWarningFunc == nil {
		panic("ClienterMock.SendWarningFunc: method is nil but Clienter.SendWarning was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}{
		Ctx:     ctx,
		Title:   title,
		Details: details,
		Links:   links,
	}
	mock.lockSendWarning.Lock()
	mock.calls.SendWarning = append(mock.calls.SendWarning, callInfo)
	mock.lockSendWarning.Unlock()
	return mock.SendWarningFunc(ctx, title, details, links)
}

// SendWarningCalls gets all the calls that were made to SendWarning.
// Check the length with:
//
//	len(mockedClienter.SendWarningCalls())
func (mock *ClienterMock) SendWarningCalls() []struct {
	Ctx     context.Context
	Title   string
	Details []slack.Detail
	Links   []slack.Link
} {
	var calls []struct {
		Ctx     context.Context
		Title   string
		Details []slack.Detail
		Links   []slack.Link
	}
	mock.lockSendWarning.RLock()
	calls = mock.calls.SendWarning
	mock.lockSendWarning.RUnlock()
	return calls
}

// UpdateMessage calls UpdateMessageFunc.
func (mock *ClienterMock) UpdateMessage(ctx context.Context, ref *slack.MessageRef, title string, err error, details []slack.Detail, links []slack.Link, color slack.Colour, emoji slack.Emoji) (*slack.MessageRef, error) {
	if mock.UpdateMessageFunc == nil {
		panic("ClienterMock.UpdateMessageFunc: method is nil but Clienter.UpdateMessage was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Title   string
		Err     error
		Details []slack.Detail
		Links   []slack.Link
		Color   slack.Colour
		Emoji   slack.Emoji
	}{
		Ctx:     ctx,
		Ref:     ref,
		Title:   title,
		Err:     err,
		Details: details,
		Links:   links,
		Color:   color,
		Emoji:   emoji,
	}
	mock.lockUpdateMessage.Lock()
	mock.calls.UpdateMessage = append(mock.calls.UpdateMessage, callInfo)
	mock.lockUpdateMessage.Unlock()
	return mock.UpdateMessageFunc(ctx, ref, title, err, details, links, color, emoji)
}

// UpdateMessageCalls gets all the calls that were made to UpdateMessage.
// Check the length with:
//
//	len(mockedClienter.UpdateMessageCalls())
func (mock *ClienterMock) UpdateMessageCalls() []struct {
	Ctx     context.Context
	Ref     *slack.MessageRef
	Title   string
	Err     error
	Details []slack.Detail
	Links   []slack.Link
	Color   slack.Colour
	Emoji   slack.Emoji
} {
	var calls []struct {
		Ctx     context.Context
		Ref     *slack.MessageRef
		Title   string
		Err     error
		Details []slack.Detail
		Links   []slack.Link
		Color   slack.Colour
		Emoji   slack.Emoji
	}
	mock.lockUpdateMessage.RLock()
	calls = mock.calls.UpdateMessage
	mock.lockUpdateMessage.RUnlock()
	return calls
}
