version: '3.3'
services:
  dis-bundle-api:
    build:
      context: ../../../../dis-bundle-api
      dockerfile: Dockerfile.local
    command:
      - go
      - test
      - -cover
      - -race
      - -coverpkg=github.com/ONSdigital/dis-bundle-api/...
      - -component
    volumes:
      - ../../../:/dis-bundle-api
    ports:
      - 26300:26300
    environment:
      BIND_ADDR: ":29800"
      SERVICE_AUTH_TOKEN: "testToken"
      COMPONENT_TEST_USE_LOG_FILE: "${COMPONENT_TEST_USE_LOG_FILE-false}"
      GOTOOLCHAIN: auto
      