// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	disbundleapiauth "github.com/ONSdigital/dis-bundle-api/auth"
	"github.com/ONSdigital/dis-bundle-api/config"
	"github.com/ONSdigital/dis-bundle-api/service"
	"github.com/ONSdigital/dis-bundle-api/store"
	"github.com/ONSdigital/dp-api-clients-go/v2/health"
	authorisation "github.com/ONSdigital/dp-authorisation/v2/authorisation"
	datasetAPISDK "github.com/ONSdigital/dp-dataset-api/sdk"
	"net/http"
	"sync"
)

// Ensure, that InitialiserMock does implement service.Initialiser.
// If this is not the case, regenerate this file with moq.
var _ service.Initialiser = &InitialiserMock{}

// InitialiserMock is a mock implementation of service.Initialiser.
//
//	func TestSomethingThatUsesInitialiser(t *testing.T) {
//
//		// make and configure a mocked service.Initialiser
//		mockedInitialiser := &InitialiserMock{
//			DoGetAuthorisationMiddlewareFunc: func(ctx context.Context, authorisationConfig *authorisation.Config) (disbundleapiauth.AuthorisationMiddleware, error) {
//				panic("mock out the DoGetAuthorisationMiddleware method")
//			},
//			DoGetDatasetAPIClientFunc: func(datasetAPIURL string) datasetAPISDK.Clienter {
//				panic("mock out the DoGetDatasetAPIClient method")
//			},
//			DoGetHTTPServerFunc: func(bindAddr string, router http.Handler) service.HTTPServer {
//				panic("mock out the DoGetHTTPServer method")
//			},
//			DoGetHealthCheckFunc: func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
//				panic("mock out the DoGetHealthCheck method")
//			},
//			DoGetHealthClientFunc: func(name string, url string) *health.Client {
//				panic("mock out the DoGetHealthClient method")
//			},
//			DoGetMongoDBFunc: func(ctx context.Context, cfg config.MongoConfig) (store.MongoDB, error) {
//				panic("mock out the DoGetMongoDB method")
//			},
//		}
//
//		// use mockedInitialiser in code that requires service.Initialiser
//		// and then make assertions.
//
//	}
type InitialiserMock struct {
	// DoGetAuthorisationMiddlewareFunc mocks the DoGetAuthorisationMiddleware method.
	DoGetAuthorisationMiddlewareFunc func(ctx context.Context, authorisationConfig *authorisation.Config) (disbundleapiauth.AuthorisationMiddleware, error)

	// DoGetDatasetAPIClientFunc mocks the DoGetDatasetAPIClient method.
	DoGetDatasetAPIClientFunc func(datasetAPIURL string) datasetAPISDK.Clienter

	// DoGetHTTPServerFunc mocks the DoGetHTTPServer method.
	DoGetHTTPServerFunc func(bindAddr string, router http.Handler) service.HTTPServer

	// DoGetHealthCheckFunc mocks the DoGetHealthCheck method.
	DoGetHealthCheckFunc func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error)

	// DoGetHealthClientFunc mocks the DoGetHealthClient method.
	DoGetHealthClientFunc func(name string, url string) *health.Client

	// DoGetMongoDBFunc mocks the DoGetMongoDB method.
	DoGetMongoDBFunc func(ctx context.Context, cfg config.MongoConfig) (store.MongoDB, error)

	// calls tracks calls to the methods.
	calls struct {
		// DoGetAuthorisationMiddleware holds details about calls to the DoGetAuthorisationMiddleware method.
		DoGetAuthorisationMiddleware []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthorisationConfig is the authorisationConfig argument value.
			AuthorisationConfig *authorisation.Config
		}
		// DoGetDatasetAPIClient holds details about calls to the DoGetDatasetAPIClient method.
		DoGetDatasetAPIClient []struct {
			// DatasetAPIURL is the datasetAPIURL argument value.
			DatasetAPIURL string
		}
		// DoGetHTTPServer holds details about calls to the DoGetHTTPServer method.
		DoGetHTTPServer []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Router is the router argument value.
			Router http.Handler
		}
		// DoGetHealthCheck holds details about calls to the DoGetHealthCheck method.
		DoGetHealthCheck []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// BuildTime is the buildTime argument value.
			BuildTime string
			// GitCommit is the gitCommit argument value.
			GitCommit string
			// Version is the version argument value.
			Version string
		}
		// DoGetHealthClient holds details about calls to the DoGetHealthClient method.
		DoGetHealthClient []struct {
			// Name is the name argument value.
			Name string
			// URL is the url argument value.
			URL string
		}
		// DoGetMongoDB holds details about calls to the DoGetMongoDB method.
		DoGetMongoDB []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cfg is the cfg argument value.
			Cfg config.MongoConfig
		}
	}
	lockDoGetAuthorisationMiddleware sync.RWMutex
	lockDoGetDatasetAPIClient        sync.RWMutex
	lockDoGetHTTPServer              sync.RWMutex
	lockDoGetHealthCheck             sync.RWMutex
	lockDoGetHealthClient            sync.RWMutex
	lockDoGetMongoDB                 sync.RWMutex
}

// DoGetAuthorisationMiddleware calls DoGetAuthorisationMiddlewareFunc.
func (mock *InitialiserMock) DoGetAuthorisationMiddleware(ctx context.Context, authorisationConfig *authorisation.Config) (disbundleapiauth.AuthorisationMiddleware, error) {
	if mock.DoGetAuthorisationMiddlewareFunc == nil {
		panic("InitialiserMock.DoGetAuthorisationMiddlewareFunc: method is nil but Initialiser.DoGetAuthorisationMiddleware was just called")
	}
	callInfo := struct {
		Ctx                 context.Context
		AuthorisationConfig *authorisation.Config
	}{
		Ctx:                 ctx,
		AuthorisationConfig: authorisationConfig,
	}
	mock.lockDoGetAuthorisationMiddleware.Lock()
	mock.calls.DoGetAuthorisationMiddleware = append(mock.calls.DoGetAuthorisationMiddleware, callInfo)
	mock.lockDoGetAuthorisationMiddleware.Unlock()
	return mock.DoGetAuthorisationMiddlewareFunc(ctx, authorisationConfig)
}

// DoGetAuthorisationMiddlewareCalls gets all the calls that were made to DoGetAuthorisationMiddleware.
// Check the length with:
//
//	len(mockedInitialiser.DoGetAuthorisationMiddlewareCalls())
func (mock *InitialiserMock) DoGetAuthorisationMiddlewareCalls() []struct {
	Ctx                 context.Context
	AuthorisationConfig *authorisation.Config
} {
	var calls []struct {
		Ctx                 context.Context
		AuthorisationConfig *authorisation.Config
	}
	mock.lockDoGetAuthorisationMiddleware.RLock()
	calls = mock.calls.DoGetAuthorisationMiddleware
	mock.lockDoGetAuthorisationMiddleware.RUnlock()
	return calls
}

// DoGetDatasetAPIClient calls DoGetDatasetAPIClientFunc.
func (mock *InitialiserMock) DoGetDatasetAPIClient(datasetAPIURL string) datasetAPISDK.Clienter {
	if mock.DoGetDatasetAPIClientFunc == nil {
		panic("InitialiserMock.DoGetDatasetAPIClientFunc: method is nil but Initialiser.DoGetDatasetAPIClient was just called")
	}
	callInfo := struct {
		DatasetAPIURL string
	}{
		DatasetAPIURL: datasetAPIURL,
	}
	mock.lockDoGetDatasetAPIClient.Lock()
	mock.calls.DoGetDatasetAPIClient = append(mock.calls.DoGetDatasetAPIClient, callInfo)
	mock.lockDoGetDatasetAPIClient.Unlock()
	return mock.DoGetDatasetAPIClientFunc(datasetAPIURL)
}

// DoGetDatasetAPIClientCalls gets all the calls that were made to DoGetDatasetAPIClient.
// Check the length with:
//
//	len(mockedInitialiser.DoGetDatasetAPIClientCalls())
func (mock *InitialiserMock) DoGetDatasetAPIClientCalls() []struct {
	DatasetAPIURL string
} {
	var calls []struct {
		DatasetAPIURL string
	}
	mock.lockDoGetDatasetAPIClient.RLock()
	calls = mock.calls.DoGetDatasetAPIClient
	mock.lockDoGetDatasetAPIClient.RUnlock()
	return calls
}

// DoGetHTTPServer calls DoGetHTTPServerFunc.
func (mock *InitialiserMock) DoGetHTTPServer(bindAddr string, router http.Handler) service.HTTPServer {
	if mock.DoGetHTTPServerFunc == nil {
		panic("InitialiserMock.DoGetHTTPServerFunc: method is nil but Initialiser.DoGetHTTPServer was just called")
	}
	callInfo := struct {
		BindAddr string
		Router   http.Handler
	}{
		BindAddr: bindAddr,
		Router:   router,
	}
	mock.lockDoGetHTTPServer.Lock()
	mock.calls.DoGetHTTPServer = append(mock.calls.DoGetHTTPServer, callInfo)
	mock.lockDoGetHTTPServer.Unlock()
	return mock.DoGetHTTPServerFunc(bindAddr, router)
}

// DoGetHTTPServerCalls gets all the calls that were made to DoGetHTTPServer.
// Check the length with:
//
//	len(mockedInitialiser.DoGetHTTPServerCalls())
func (mock *InitialiserMock) DoGetHTTPServerCalls() []struct {
	BindAddr string
	Router   http.Handler
} {
	var calls []struct {
		BindAddr string
		Router   http.Handler
	}
	mock.lockDoGetHTTPServer.RLock()
	calls = mock.calls.DoGetHTTPServer
	mock.lockDoGetHTTPServer.RUnlock()
	return calls
}

// DoGetHealthCheck calls DoGetHealthCheckFunc.
func (mock *InitialiserMock) DoGetHealthCheck(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
	if mock.DoGetHealthCheckFunc == nil {
		panic("InitialiserMock.DoGetHealthCheckFunc: method is nil but Initialiser.DoGetHealthCheck was just called")
	}
	callInfo := struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}{
		Cfg:       cfg,
		BuildTime: buildTime,
		GitCommit: gitCommit,
		Version:   version,
	}
	mock.lockDoGetHealthCheck.Lock()
	mock.calls.DoGetHealthCheck = append(mock.calls.DoGetHealthCheck, callInfo)
	mock.lockDoGetHealthCheck.Unlock()
	return mock.DoGetHealthCheckFunc(cfg, buildTime, gitCommit, version)
}

// DoGetHealthCheckCalls gets all the calls that were made to DoGetHealthCheck.
// Check the length with:
//
//	len(mockedInitialiser.DoGetHealthCheckCalls())
func (mock *InitialiserMock) DoGetHealthCheckCalls() []struct {
	Cfg       *config.Config
	BuildTime string
	GitCommit string
	Version   string
} {
	var calls []struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}
	mock.lockDoGetHealthCheck.RLock()
	calls = mock.calls.DoGetHealthCheck
	mock.lockDoGetHealthCheck.RUnlock()
	return calls
}

// DoGetHealthClient calls DoGetHealthClientFunc.
func (mock *InitialiserMock) DoGetHealthClient(name string, url string) *health.Client {
	if mock.DoGetHealthClientFunc == nil {
		panic("InitialiserMock.DoGetHealthClientFunc: method is nil but Initialiser.DoGetHealthClient was just called")
	}
	callInfo := struct {
		Name string
		URL  string
	}{
		Name: name,
		URL:  url,
	}
	mock.lockDoGetHealthClient.Lock()
	mock.calls.DoGetHealthClient = append(mock.calls.DoGetHealthClient, callInfo)
	mock.lockDoGetHealthClient.Unlock()
	return mock.DoGetHealthClientFunc(name, url)
}

// DoGetHealthClientCalls gets all the calls that were made to DoGetHealthClient.
// Check the length with:
//
//	len(mockedInitialiser.DoGetHealthClientCalls())
func (mock *InitialiserMock) DoGetHealthClientCalls() []struct {
	Name string
	URL  string
} {
	var calls []struct {
		Name string
		URL  string
	}
	mock.lockDoGetHealthClient.RLock()
	calls = mock.calls.DoGetHealthClient
	mock.lockDoGetHealthClient.RUnlock()
	return calls
}

// DoGetMongoDB calls DoGetMongoDBFunc.
func (mock *InitialiserMock) DoGetMongoDB(ctx context.Context, cfg config.MongoConfig) (store.MongoDB, error) {
	if mock.DoGetMongoDBFunc == nil {
		panic("InitialiserMock.DoGetMongoDBFunc: method is nil but Initialiser.DoGetMongoDB was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cfg config.MongoConfig
	}{
		Ctx: ctx,
		Cfg: cfg,
	}
	mock.lockDoGetMongoDB.Lock()
	mock.calls.DoGetMongoDB = append(mock.calls.DoGetMongoDB, callInfo)
	mock.lockDoGetMongoDB.Unlock()
	return mock.DoGetMongoDBFunc(ctx, cfg)
}

// DoGetMongoDBCalls gets all the calls that were made to DoGetMongoDB.
// Check the length with:
//
//	len(mockedInitialiser.DoGetMongoDBCalls())
func (mock *InitialiserMock) DoGetMongoDBCalls() []struct {
	Ctx context.Context
	Cfg config.MongoConfig
} {
	var calls []struct {
		Ctx context.Context
		Cfg config.MongoConfig
	}
	mock.lockDoGetMongoDB.RLock()
	calls = mock.calls.DoGetMongoDB
	mock.lockDoGetMongoDB.RUnlock()
	return calls
}
