---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.2-bullseye

inputs:
  - name: dis-bundle-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-bundle-api/ci/scripts/build.sh
