// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storetest

import (
	"context"
	"github.com/ONSdigital/dis-bundle-api/models"
	"github.com/ONSdigital/dis-bundle-api/store"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that MongoDBMock does implement store.MongoDB.
// If this is not the case, regenerate this file with moq.
var _ store.MongoDB = &MongoDBMock{}

// MongoDBMock is a mock implementation of store.MongoDB.
//
//	func TestSomethingThatUsesMongoDB(t *testing.T) {
//
//		// make and configure a mocked store.MongoDB
//		mockedMongoDB := &MongoDBMock{
//			CheckAllBundleContentsAreApprovedFunc: func(ctx context.Context, bundleID string) (bool, error) {
//				panic("mock out the CheckAllBundleContentsAreApproved method")
//			},
//			CheckerFunc: func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CloseFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Close method")
//			},
//			CreateBundleFunc: func(ctx context.Context, bundle *models.Bundle) error {
//				panic("mock out the CreateBundle method")
//			},
//			CreateBundleEventFunc: func(ctx context.Context, event *models.Event) error {
//				panic("mock out the CreateBundleEvent method")
//			},
//			GetBundleByTitleFunc: func(ctx context.Context, title string) (*models.Bundle, error) {
//				panic("mock out the GetBundleByTitle method")
//			},
//			ListBundlesFunc: func(ctx context.Context, offset int, limit int) ([]*models.Bundle, int, error) {
//				panic("mock out the ListBundles method")
//			},
//		}
//
//		// use mockedMongoDB in code that requires store.MongoDB
//		// and then make assertions.
//
//	}
type MongoDBMock struct {
	// CheckAllBundleContentsAreApprovedFunc mocks the CheckAllBundleContentsAreApproved method.
	CheckAllBundleContentsAreApprovedFunc func(ctx context.Context, bundleID string) (bool, error)

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(contextMoqParam context.Context) error

	// CreateBundleFunc mocks the CreateBundle method.
	CreateBundleFunc func(ctx context.Context, bundle *models.Bundle) error

	// CreateBundleEventFunc mocks the CreateBundleEvent method.
	CreateBundleEventFunc func(ctx context.Context, event *models.Event) error

	// GetBundleByTitleFunc mocks the GetBundleByTitle method.
	GetBundleByTitleFunc func(ctx context.Context, title string) (*models.Bundle, error)

	// ListBundlesFunc mocks the ListBundles method.
	ListBundlesFunc func(ctx context.Context, offset int, limit int) ([]*models.Bundle, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckAllBundleContentsAreApproved holds details about calls to the CheckAllBundleContentsAreApproved method.
		CheckAllBundleContentsAreApproved []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BundleID is the bundleID argument value.
			BundleID string
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CheckState is the checkState argument value.
			CheckState *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// CreateBundle holds details about calls to the CreateBundle method.
		CreateBundle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bundle is the bundle argument value.
			Bundle *models.Bundle
		}
		// CreateBundleEvent holds details about calls to the CreateBundleEvent method.
		CreateBundleEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *models.Event
		}
		// GetBundleByTitle holds details about calls to the GetBundleByTitle method.
		GetBundleByTitle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
		}
		// ListBundles holds details about calls to the ListBundles method.
		ListBundles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCheckAllBundleContentsAreApproved sync.RWMutex
	lockChecker                           sync.RWMutex
	lockClose                             sync.RWMutex
	lockCreateBundle                      sync.RWMutex
	lockCreateBundleEvent                 sync.RWMutex
	lockGetBundleByTitle                  sync.RWMutex
	lockListBundles                       sync.RWMutex
}

// CheckAllBundleContentsAreApproved calls CheckAllBundleContentsAreApprovedFunc.
func (mock *MongoDBMock) CheckAllBundleContentsAreApproved(ctx context.Context, bundleID string) (bool, error) {
	if mock.CheckAllBundleContentsAreApprovedFunc == nil {
		panic("MongoDBMock.CheckAllBundleContentsAreApprovedFunc: method is nil but MongoDB.CheckAllBundleContentsAreApproved was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BundleID string
	}{
		Ctx:      ctx,
		BundleID: bundleID,
	}
	mock.lockCheckAllBundleContentsAreApproved.Lock()
	mock.calls.CheckAllBundleContentsAreApproved = append(mock.calls.CheckAllBundleContentsAreApproved, callInfo)
	mock.lockCheckAllBundleContentsAreApproved.Unlock()
	return mock.CheckAllBundleContentsAreApprovedFunc(ctx, bundleID)
}

// CheckAllBundleContentsAreApprovedCalls gets all the calls that were made to CheckAllBundleContentsAreApproved.
// Check the length with:
//
//	len(mockedMongoDB.CheckAllBundleContentsAreApprovedCalls())
func (mock *MongoDBMock) CheckAllBundleContentsAreApprovedCalls() []struct {
	Ctx      context.Context
	BundleID string
} {
	var calls []struct {
		Ctx      context.Context
		BundleID string
	}
	mock.lockCheckAllBundleContentsAreApproved.RLock()
	calls = mock.calls.CheckAllBundleContentsAreApproved
	mock.lockCheckAllBundleContentsAreApproved.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *MongoDBMock) Checker(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("MongoDBMock.CheckerFunc: method is nil but MongoDB.Checker was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}{
		ContextMoqParam: contextMoqParam,
		CheckState:      checkState,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(contextMoqParam, checkState)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedMongoDB.CheckerCalls())
func (mock *MongoDBMock) CheckerCalls() []struct {
	ContextMoqParam context.Context
	CheckState      *healthcheck.CheckState
} {
	var calls []struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MongoDBMock) Close(contextMoqParam context.Context) error {
	if mock.CloseFunc == nil {
		panic("MongoDBMock.CloseFunc: method is nil but MongoDB.Close was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(contextMoqParam)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMongoDB.CloseCalls())
func (mock *MongoDBMock) CloseCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CreateBundle calls CreateBundleFunc.
func (mock *MongoDBMock) CreateBundle(ctx context.Context, bundle *models.Bundle) error {
	if mock.CreateBundleFunc == nil {
		panic("MongoDBMock.CreateBundleFunc: method is nil but MongoDB.CreateBundle was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bundle *models.Bundle
	}{
		Ctx:    ctx,
		Bundle: bundle,
	}
	mock.lockCreateBundle.Lock()
	mock.calls.CreateBundle = append(mock.calls.CreateBundle, callInfo)
	mock.lockCreateBundle.Unlock()
	return mock.CreateBundleFunc(ctx, bundle)
}

// CreateBundleCalls gets all the calls that were made to CreateBundle.
// Check the length with:
//
//	len(mockedMongoDB.CreateBundleCalls())
func (mock *MongoDBMock) CreateBundleCalls() []struct {
	Ctx    context.Context
	Bundle *models.Bundle
} {
	var calls []struct {
		Ctx    context.Context
		Bundle *models.Bundle
	}
	mock.lockCreateBundle.RLock()
	calls = mock.calls.CreateBundle
	mock.lockCreateBundle.RUnlock()
	return calls
}

// CreateBundleEvent calls CreateBundleEventFunc.
func (mock *MongoDBMock) CreateBundleEvent(ctx context.Context, event *models.Event) error {
	if mock.CreateBundleEventFunc == nil {
		panic("MongoDBMock.CreateBundleEventFunc: method is nil but MongoDB.CreateBundleEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *models.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockCreateBundleEvent.Lock()
	mock.calls.CreateBundleEvent = append(mock.calls.CreateBundleEvent, callInfo)
	mock.lockCreateBundleEvent.Unlock()
	return mock.CreateBundleEventFunc(ctx, event)
}

// CreateBundleEventCalls gets all the calls that were made to CreateBundleEvent.
// Check the length with:
//
//	len(mockedMongoDB.CreateBundleEventCalls())
func (mock *MongoDBMock) CreateBundleEventCalls() []struct {
	Ctx   context.Context
	Event *models.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event *models.Event
	}
	mock.lockCreateBundleEvent.RLock()
	calls = mock.calls.CreateBundleEvent
	mock.lockCreateBundleEvent.RUnlock()
	return calls
}

// GetBundleByTitle calls GetBundleByTitleFunc.
func (mock *MongoDBMock) GetBundleByTitle(ctx context.Context, title string) (*models.Bundle, error) {
	if mock.GetBundleByTitleFunc == nil {
		panic("MongoDBMock.GetBundleByTitleFunc: method is nil but MongoDB.GetBundleByTitle was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Title string
	}{
		Ctx:   ctx,
		Title: title,
	}
	mock.lockGetBundleByTitle.Lock()
	mock.calls.GetBundleByTitle = append(mock.calls.GetBundleByTitle, callInfo)
	mock.lockGetBundleByTitle.Unlock()
	return mock.GetBundleByTitleFunc(ctx, title)
}

// GetBundleByTitleCalls gets all the calls that were made to GetBundleByTitle.
// Check the length with:
//
//	len(mockedMongoDB.GetBundleByTitleCalls())
func (mock *MongoDBMock) GetBundleByTitleCalls() []struct {
	Ctx   context.Context
	Title string
} {
	var calls []struct {
		Ctx   context.Context
		Title string
	}
	mock.lockGetBundleByTitle.RLock()
	calls = mock.calls.GetBundleByTitle
	mock.lockGetBundleByTitle.RUnlock()
	return calls
}

// ListBundles calls ListBundlesFunc.
func (mock *MongoDBMock) ListBundles(ctx context.Context, offset int, limit int) ([]*models.Bundle, int, error) {
	if mock.ListBundlesFunc == nil {
		panic("MongoDBMock.ListBundlesFunc: method is nil but MongoDB.ListBundles was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}{
		Ctx:    ctx,
		Offset: offset,
		Limit:  limit,
	}
	mock.lockListBundles.Lock()
	mock.calls.ListBundles = append(mock.calls.ListBundles, callInfo)
	mock.lockListBundles.Unlock()
	return mock.ListBundlesFunc(ctx, offset, limit)
}

// ListBundlesCalls gets all the calls that were made to ListBundles.
// Check the length with:
//
//	len(mockedMongoDB.ListBundlesCalls())
func (mock *MongoDBMock) ListBundlesCalls() []struct {
	Ctx    context.Context
	Offset int
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Offset int
		Limit  int
	}
	mock.lockListBundles.RLock()
	calls = mock.calls.ListBundles
	mock.lockListBundles.RUnlock()
	return calls
}
